apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: limkeunhyeok/my-space-backend
    newName: limkeunhyeok/my-space-backend
    newTag: latest
