apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: chungdaeking/my-space-frontend
    newName: chungdaeking/my-space-frontend
    newTag: sha-a5d2891

