apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-space-ai
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/lkh-space/homelab-infra.git
    targetRevision: main
    path: k8s/apps/ai
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
