apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-space-api
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: my-space-api=chungdaeking/my-space-api
    argocd-image-updater.argoproj.io/my-space-api.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/lkh-space/homelab-infra.git
    targetRevision: main
    path: k8s/apps/api
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
