apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-space-apps
  namespace: argocd
  labels:
    app.kubernetes.io/name: my-space-apps
    app.kubernetes.io/part-of: homelab-apps
spec:
  project: default
  source:
    repoURL: https://github.com/limkeunhyeok/homelab-infra.git
    targetRevision: main
    path: k8s/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
