apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-space-api-ingress
  namespace: apps
  labels:
    app: my-space-api
    app.kubernetes.io/name: my-space-api
    app.kubernetes.io/part-of: homelab-apps
  annotations:
    cert-manager.io/cluster-issuer: homelab-ca-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: apps-authelia-forwardauth@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - api.homelab.local
      secretName: backend-tls
  rules:
    - host: api.homelab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-space-api
                port:
                  number: 3000
